// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCs6uUk0Yy4AI4j1IOvB3LMqlpxwW_iPE',
    appId: '1:563374130954:web:bdaa28d51b7b3ae9a09cf3',
    messagingSenderId: '563374130954',
    projectId: 'cream-and-cookies',
    authDomain: 'cream-and-cookies.firebaseapp.com',
    storageBucket: 'cream-and-cookies.firebasestorage.app',
    measurementId: 'G-M78GKEN24B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodnJadQhlVryB4EQgaaRb0v3t1hNi9GQ',
    appId: '1:563374130954:android:b44f81a970e5ec2ba09cf3',
    messagingSenderId: '563374130954',
    projectId: 'cream-and-cookies',
    storageBucket: 'cream-and-cookies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnK_P1oqwqnda4Gkz0aWt_t_c9J4nW54',
    appId: '1:563374130954:ios:0852146dc5b54199a09cf3',
    messagingSenderId: '563374130954',
    projectId: 'cream-and-cookies',
    storageBucket: 'cream-and-cookies.firebasestorage.app',
    iosClientId: '563374130954-1goi5handijibqhcfvi9r6h2jhmi7k18.apps.googleusercontent.com',
    iosBundleId: 'com.example.authexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnK_P1oqwqnda4Gkz0aWt_t_c9J4nW54',
    appId: '1:563374130954:ios:0852146dc5b54199a09cf3',
    messagingSenderId: '563374130954',
    projectId: 'cream-and-cookies',
    storageBucket: 'cream-and-cookies.firebasestorage.app',
    iosClientId: '563374130954-1goi5handijibqhcfvi9r6h2jhmi7k18.apps.googleusercontent.com',
    iosBundleId: 'com.example.authexample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCs6uUk0Yy4AI4j1IOvB3LMqlpxwW_iPE',
    appId: '1:563374130954:web:51947a76e2c54d9aa09cf3',
    messagingSenderId: '563374130954',
    projectId: 'cream-and-cookies',
    authDomain: 'cream-and-cookies.firebaseapp.com',
    storageBucket: 'cream-and-cookies.firebasestorage.app',
    measurementId: 'G-MT6X4WRR70',
  );
}
